services:
  mysql:
    image: mysql:latest
    container_name: Prueba
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: Supermercado
      MYSQL_USER: user
      MYSQL_PASSWORD: "1234"
    ports:
      - "3308:3306"
    volumes:
      - C:\Users\migue\Desktop\BDArquitectura:/var/lib/mysql
      - C:\Users\migue\Desktop\arq\init:/docker-entrypoint-initdb.d



